# This spec file was generated by KDevelop
# Please report any problem to KDevelop Team <kdevelop-devel@kdevelop.org>
# Thanks to Matthias Saou for his explanations on http://freshrpms.net/docs/fight.html

Name: kasablanca
Version: 0.3.1
Release: 1
Vendor: Me
Copyright: GPL
Summary: kde ftp klient
Group: Applications/System
Packager: x
BuildRoot: %{_tmppath}/%{name}-root
Source: kasablanca-0.3.1.tar.gz

%description
y

%prep
%setup
CFLAGS="$RPM_OPT_FLAGS" CXXFLAGS="$RPM_OPT_FLAGS" ./configure \
--target=i586

%build
%configure
make

%install
rm -rf %{buildroot}
%makeinstall

%clean
rm -rf %{buildroot}

%post -p /sbin/ldconfig
%postun -p /sbin/ldconfig
%files
%defattr(-, root, root)
%doc AUTHORS COPYING ChangeLog NEWS README TODO
%{_bindir}/*
%{_libdir}/*.so.*
%{_datadir}/%{name}
%{_mandir}/man8/*
%changelog

